title: Scala Explained!
description: Scala tips and code snippets.
theme: jekyll-theme-minimal
logo: assets/img/logo.svg
markdown: kramdown
kramdown:
  toc_levels: "2,3,4,5,6"
show_downloads: true
github:
  fakeroot_url: /scala-explained
  repository_url: https://github.com/yoeo/scala-explained/
  owner_url: https://github.com/yoeo/
  owner_name: yoeo
  owner_fullname: "Y. Somda"
  zip_url: https://github.com/yoeo/scala-explained/archive/master.zip
  tar_url: https://github.com/yoeo/scala-explained/archive/master.tar.gz
  sitemenu:
    - ""
    - syntax
    - literals
    - keywords
    - symbols
    - library
