title: Scala Explained!
description: Looking for a deep understanding of Scala language.
#theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal
minimal_mistakes_skin: "default"
markdown: kramdown
kramdown: 
  toc_levels: "2,3,4,5,6"
show_downloads: true
github:
  repo: yoeo/scala-explained
  projects: https://github.com/yoeo/scala-explained/
