title: Scala Explained!
description: A deep understanding of Scala language.
theme: jekyll-theme-minimal
logo: assets/img/logo.png
markdown: kramdown
kramdown:
  toc_levels: "2,3,4,5,6"
show_downloads: true
github:
  fakeroot_url: /scala-explained
  repository_url: https://github.com/yoeo/scala-explained/
  owner_url: https://github.com/yoeo/
  owner_name: yoeo
  zip_url: https://github.com/yoeo/scala-explained/archive/master.zip
  tar_url: https://github.com/yoeo/scala-explained/archive/master.tar.gz
