title: Scala Explained!
description: Looking for a deep understanding of Scala language.
theme: jekyll-theme-cayman
#remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "default"
markdown: kramdown
kramdown: 
  toc_levels: "2,3,4,5,6"
show_downloads: true
github:
  repo: scalaexplained/scalaexplained.github.io
  projects: https://github.com/scalaexplained/
